esgc/br/gov/pe/pm/sgc/bean/AguaBean.java
package br.gov.pe.pm.sgc.bean;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;

import br.gov.pe.pm.sgc.model.Agua;
import br.gov.pe.pm.sgc.rn.AguaRn;


@Named("aguaBean")
@ViewScoped
public class AguaBean implements Serializable {
    
	private static final long serialVersionUID = 1L;
	
	
//private List<Agua> aguas;
private int anoCorrente = new GregorianCalendar().get(java.util.Calendar.YEAR);
private int anoAnterior = anoCorrente - 1;
private int mes = new GregorianCalendar().get(java.util.Calendar.MONTH);
private String mes1;
private String mes2;
private String mes3;
    
   
    
    
    
    
    public List<Agua> getAguas() {
    	return new AguaRn().listar();
    }
     
    /*public String getLastYearTotal() {
    	double total = 0.0;
 
        for(Agua agua : getAguas()) {
            total += agua.getLastYearAgua();
        }
 
        return new DecimalFormat("###,###.00").format(total);
    }*/
    
  /*  public String getThisYearTotal() {
        double total = 0.0;
 
        for(Agua agua : getAguas()) {
            total += agua.getThisYearAgua();
           
        }
       
 
        return new DecimalFormat("###,###.00").format(total);
    }*/

	public int getAnoCorrente() {
		return anoCorrente;
	}

	public void setAnoCorrente(int anoCorrente) {
		this.anoCorrente = anoCorrente;
	}

	public int getAnoAnterior() {
		return anoAnterior;
	}

	public void setAnoAnterior(int anoAnterior) {
		this.anoAnterior = anoAnterior;
	}
	
	public String getDataAtual() {        
	    SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
	    Date dataAtual = new Date(System.currentTimeMillis());
	    return sd.format(dataAtual);        
	
	}

	public String getMes1() {
		return mes1;
	}

	public String getMes2() {
		return mes2;
	}

	public String getMes3() {
		return mes3;
	}

    public void carregarMes () {
    	
    	if (mes>0)
    	{
    	   switch (mes)
    	    {
    	   	  case 1:
    	  	   mes3 = "Jan";
    	  	   mes2 = "Dez";
    	  	   mes1 = "Nov";break;
    	  	  case 2:
    	  	   mes3 = "Fev";
      	  	   mes2 = "Jan";
      	  	   mes1 = "Dez";break;
    	  	  case 3:
    	  	   mes3 = "Mar";
      	  	   mes2 = "Fev";
      	  	   mes1 = "Jan";break;
    	  	  case 4:
       	  	   mes3 = "Abr";
      	  	   mes2 = "Mar";
      	  	   mes1 = "Fev";break;
    	  	  case 5:
       	  	   mes3 = "Mai";
      	  	   mes2 = "Abr";
      	  	   mes1 = "Mar";break;
    	  	  case 6:
       	  	   mes3 = "Jun";
      	  	   mes2 = "Mai";
      	  	   mes1 = "Abr";break;
    	  	  case 7:
       	  	   mes3 = "Jul";
      	  	   mes2 = "Jun";
      	  	   mes1 = "Mai";break;
    	  	  case 8:
       	  	   mes3 = "Ago";
      	  	   mes2 = "Jul";
      	  	   mes1 = "Jun";break;
    	  	  case 9:
       	  	   mes3 = "Set";
      	  	   mes2 = "Ago";
      	  	   mes1 = "Jul";break;
    	  	  case 10:
       	  	   mes3 = "Out";
      	  	   mes2 = "Set";
      	  	   mes1 = "Jul";break;
    	  	  case 11:
       	  	   mes3 = "Nov";
      	  	   mes2 = "Out";
      	  	   mes1 = "Set";break;
    	  	  case 12:
       	  	   mes3 = "Dez";
      	  	   mes2 = "Nov";
      	  	   mes1 = "Out";break;

    	  	 default:System.out.println ("Nao e valido");
    	 	}	 
    	   }
    	   else System.out.println ("Valor nao valido");
    	 }
    
    public void preProcessPDF(Object document) throws IOException, BadElementException, DocumentException {
        Document pdf = (Document) document;
        pdf.open();
        pdf.setPageSize(PageSize.A4);
 
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        String logo = externalContext.getRealPath("") + File.separator + "resources" + File.separator + "demo" + File.separator + "images" + File.separator + "prime_logo.png";
         
        pdf.add(Image.getInstance(logo));
    }
    	
    
    
    
    
    
    
    
    
}

esgc/br/gov/pe/pm/sgc/bean/LuzBean.java
package br.gov.pe.pm.sgc.bean;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;

import br.gov.pe.pm.sgc.model.Luz;
import br.gov.pe.pm.sgc.rn.LuzRn;

@Named("luzBean")
@ViewScoped
public class LuzBean implements Serializable {

	private static final long serialVersionUID = -215057514692187770L;
	// private List<Luz> aguas;
	private int anoCorrente = new GregorianCalendar().get(java.util.Calendar.YEAR);
	private int anoAnterior = anoCorrente - 1;
	private int mes = new GregorianCalendar().get(java.util.Calendar.MONTH);
	private String mes1;
	private String mes2;
	private String mes3;

	public List<Luz> getLuzs() {
		return new LuzRn().listar();
	}

	/*
	 * public String getLastYearTotal() { double total = 0.0;
	 * 
	 * for(Luz agua : getAguas()) { total += agua.getLastYearAgua(); }
	 * 
	 * return new DecimalFormat("###,###.00").format(total); }
	 */

	/*
	 * public String getThisYearTotal() { double total = 0.0;
	 * 
	 * for(Luz agua : getAguas()) { total += agua.getThisYearAgua();
	 * 
	 * }
	 * 
	 * 
	 * return new DecimalFormat("###,###.00").format(total); }
	 */

	public int getAnoCorrente() {
		return anoCorrente;
	}

	public void setAnoCorrente(int anoCorrente) {
		this.anoCorrente = anoCorrente;
	}

	public int getAnoAnterior() {
		return anoAnterior;
	}

	public void setAnoAnterior(int anoAnterior) {
		this.anoAnterior = anoAnterior;
	}

	public String getDataAtual() {
		SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
		Date dataAtual = new Date(System.currentTimeMillis());
		return sd.format(dataAtual);

	}

	public String getMes1() {
		return mes1;
	}

	public String getMes2() {
		return mes2;
	}

	public String getMes3() {
		return mes3;
	}

	public void carregarMes() {

		if (mes > 0) {
			switch (mes) {
			case 1:
				mes3 = "Jan";
				mes2 = "Dez";
				mes1 = "Nov";
				break;
			case 2:
				mes3 = "Fev";
				mes2 = "Jan";
				mes1 = "Dez";
				break;
			case 3:
				mes3 = "Mar";
				mes2 = "Fev";
				mes1 = "Jan";
				break;
			case 4:
				mes3 = "Abr";
				mes2 = "Mar";
				mes1 = "Fev";
				break;
			case 5:
				mes3 = "Mai";
				mes2 = "Abr";
				mes1 = "Mar";
				break;
			case 6:
				mes3 = "Jun";
				mes2 = "Mai";
				mes1 = "Abr";
				break;
			case 7:
				mes3 = "Jul";
				mes2 = "Jun";
				mes1 = "Mai";
				break;
			case 8:
				mes3 = "Ago";
				mes2 = "Jul";
				mes1 = "Jun";
				break;
			case 9:
				mes3 = "Set";
				mes2 = "Ago";
				mes1 = "Jul";
				break;
			case 10:
				mes3 = "Out";
				mes2 = "Set";
				mes1 = "Jul";
				break;
			case 11:
				mes3 = "Nov";
				mes2 = "Out";
				mes1 = "Set";
				break;
			case 12:
				mes3 = "Dez";
				mes2 = "Nov";
				mes1 = "Out";
				break;

			default:
				System.out.println("Nao e valido");
			}
		} else
			System.out.println("Valor nao valido");
	}

	public void preProcessPDF(Object document) throws IOException, BadElementException, DocumentException {
		Document pdf = (Document) document;
		pdf.open();
		pdf.setPageSize(PageSize.A4);

		ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
		String logo = externalContext.getRealPath("") + File.separator + "resources" + File.separator + "demo"
				+ File.separator + "images" + File.separator + "prime_logo.png";

		pdf.add(Image.getInstance(logo));
	}

}

esgc/src/main/java/br/gov/pe/pm/esgc/bean/AguaBean.java
package br.gov.pe.pm.esgc.bean;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;

import br.gov.pe.pm.esgc.model.Agua;
import br.gov.pe.pm.esgc.rn.AguaRn;


@Named("aguaBean")
@ViewScoped
public class AguaBean implements Serializable {
    
	private static final long serialVersionUID = 1L;
	
	
//private List<Agua> aguas;
private int anoCorrente = new GregorianCalendar().get(java.util.Calendar.YEAR);
private int anoAnterior = anoCorrente - 1;
private int mes = new GregorianCalendar().get(java.util.Calendar.MONTH);
private String mes1;
private String mes2;
private String mes3;
    
   
    
    
    
    
    public List<Agua> getAguas() {
    	return new AguaRn().listar();
    }
    
    public List<Agua> getAguasAnual() {
    	return new AguaRn().listarAnual();
    }
     
    /*public String getLastYearTotal() {
    	double total = 0.0;
 
        for(Agua agua : getAguas()) {
            total += agua.getLastYearAgua();
        }
 
        return new DecimalFormat("###,###.00").format(total);
    }*/
    
  /*  public String getThisYearTotal() {
        double total = 0.0;
 
        for(Agua agua : getAguas()) {
            total += agua.getThisYearAgua();
           
        }
       
 
        return new DecimalFormat("###,###.00").format(total);
    }*/

	public int getAnoCorrente() {
		return anoCorrente;
	}

	public void setAnoCorrente(int anoCorrente) {
		this.anoCorrente = anoCorrente;
	}

	public int getAnoAnterior() {
		return anoAnterior;
	}

	public void setAnoAnterior(int anoAnterior) {
		this.anoAnterior = anoAnterior;
	}
	
	public String getDataAtual() {        
	    SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
	    Date dataAtual = new Date(System.currentTimeMillis());
	    return sd.format(dataAtual);        
	
	}

	public String getMes1() {
		return mes1;
	}

	public String getMes2() {
		return mes2;
	}

	public String getMes3() {
		return mes3;
	}

    public void carregarMes () {
    	
    	if (mes>0)
    	{
    	   switch (mes)
    	    {
    	   	  case 1:
    	  	   mes3 = "Jan";
    	  	   mes2 = "Dez";
    	  	   mes1 = "Nov";break;
    	  	  case 2:
    	  	   mes3 = "Fev";
      	  	   mes2 = "Jan";
      	  	   mes1 = "Dez";break;
    	  	  case 3:
    	  	   mes3 = "Mar";
      	  	   mes2 = "Fev";
      	  	   mes1 = "Jan";break;
    	  	  case 4:
       	  	   mes3 = "Abr";
      	  	   mes2 = "Mar";
      	  	   mes1 = "Fev";break;
    	  	  case 5:
       	  	   mes3 = "Mai";
      	  	   mes2 = "Abr";
      	  	   mes1 = "Mar";break;
    	  	  case 6:
       	  	   mes3 = "Jun";
      	  	   mes2 = "Mai";
      	  	   mes1 = "Abr";break;
    	  	  case 7:
       	  	   mes3 = "Jul";
      	  	   mes2 = "Jun";
      	  	   mes1 = "Mai";break;
    	  	  case 8:
       	  	   mes3 = "Ago";
      	  	   mes2 = "Jul";
      	  	   mes1 = "Jun";break;
    	  	  case 9:
       	  	   mes3 = "Set";
      	  	   mes2 = "Ago";
      	  	   mes1 = "Jul";break;
    	  	  case 10:
       	  	   mes3 = "Out";
      	  	   mes2 = "Set";
      	  	   mes1 = "Jul";break;
    	  	  case 11:
       	  	   mes3 = "Nov";
      	  	   mes2 = "Out";
      	  	   mes1 = "Set";break;
    	  	  case 12:
       	  	   mes3 = "Dez";
      	  	   mes2 = "Nov";
      	  	   mes1 = "Out";break;

    	  	 default:System.out.println ("Nao e valido");
    	 	}	 
    	   }
    	   else System.out.println ("Valor nao valido");
    	 }
    
    public void preProcessPDF(Object document) throws IOException, BadElementException, DocumentException {
        Document pdf = (Document) document;
        pdf.open();
        pdf.setPageSize(PageSize.A4);
 
        ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
        String logo = externalContext.getRealPath("") + File.separator + "resources" + File.separator + "demo" + File.separator + "images" + File.separator + "prime_logo.png";
         
        pdf.add(Image.getInstance(logo));
    }
    	
    
    
    
    
    
    
    
    
}

esgc/src/main/java/br/gov/pe/pm/esgc/bean/CompesaBean.java
package br.gov.pe.pm.esgc.bean;

public class CompesaBean {

}

esgc/src/main/java/br/gov/pe/pm/esgc/bean/ConsumoBean.java
package br.gov.pe.pm.esgc.bean;


import javax.faces.bean.RequestScoped;
import javax.inject.Named;

@Named("consumoBean")
@RequestScoped
public class ConsumoBean {
	
	private Integer valorA;
	private Integer valorB;
	private Integer resultado;
	
	
	public Integer getValorA() {
		return valorA;
	}
	public void setValorA(Integer valorA) {
		this.valorA = valorA;
	}
	public Integer getValorB() {
		return valorB;
	}
	public void setValorB(Integer valorB) {
		this.valorB = valorB;
	}
	public Integer getResultado() {
		return resultado;
	}
	public void setResultado(Integer resultado) {
		this.resultado = resultado;
	}
	
	public void soma() {
		this.resultado = this.valorA + this.valorB;
		
		
	}
	

}

esgc/src/main/java/br/gov/pe/pm/esgc/bean/LuzBean.java
package br.gov.pe.pm.esgc.bean;

import java.io.File;
import java.io.IOException;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;

import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import com.itextpdf.text.BadElementException;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;

import br.gov.pe.pm.esgc.model.Luz;
import br.gov.pe.pm.esgc.rn.LuzRn;

@Named("luzBean")
@ViewScoped
public class LuzBean implements Serializable {

	private static final long serialVersionUID = -215057514692187770L;
	// private List<Luz> aguas;
	private int anoCorrente = new GregorianCalendar().get(java.util.Calendar.YEAR);
	private int anoAnterior = anoCorrente - 1;
	private int mes = new GregorianCalendar().get(java.util.Calendar.MONTH);
	private String mes1;
	private String mes2;
	private String mes3;

	public List<Luz> getLuzs() {
		return new LuzRn().listar();
	}
	
	public List<Luz> getLuzsAnual() {
		return new LuzRn().listarAnual();
	}

	/*
	 * public String getLastYearTotal() { double total = 0.0;
	 * 
	 * for(Luz agua : getAguas()) { total += agua.getLastYearAgua(); }
	 * 
	 * return new DecimalFormat("###,###.00").format(total); }
	 */

	/*
	 * public String getThisYearTotal() { double total = 0.0;
	 * 
	 * for(Luz agua : getAguas()) { total += agua.getThisYearAgua();
	 * 
	 * }
	 * 
	 * 
	 * return new DecimalFormat("###,###.00").format(total); }
	 */

	public int getAnoCorrente() {
		return anoCorrente;
	}

	public void setAnoCorrente(int anoCorrente) {
		this.anoCorrente = anoCorrente;
	}

	public int getAnoAnterior() {
		return anoAnterior;
	}

	public void setAnoAnterior(int anoAnterior) {
		this.anoAnterior = anoAnterior;
	}

	public String getDataAtual() {
		SimpleDateFormat sd = new SimpleDateFormat("dd/MM/yyyy");
		Date dataAtual = new Date(System.currentTimeMillis());
		return sd.format(dataAtual);

	}

	public String getMes1() {
		return mes1;
	}

	public String getMes2() {
		return mes2;
	}

	public String getMes3() {
		return mes3;
	}

	public void carregarMes() {

		if (mes > 0) {
			switch (mes) {
			case 1:
				mes3 = "Jan";
				mes2 = "Dez";
				mes1 = "Nov";
				break;
			case 2:
				mes3 = "Fev";
				mes2 = "Jan";
				mes1 = "Dez";
				break;
			case 3:
				mes3 = "Mar";
				mes2 = "Fev";
				mes1 = "Jan";
				break;
			case 4:
				mes3 = "Abr";
				mes2 = "Mar";
				mes1 = "Fev";
				break;
			case 5:
				mes3 = "Mai";
				mes2 = "Abr";
				mes1 = "Mar";
				break;
			case 6:
				mes3 = "Jun";
				mes2 = "Mai";
				mes1 = "Abr";
				break;
			case 7:
				mes3 = "Jul";
				mes2 = "Jun";
				mes1 = "Mai";
				break;
			case 8:
				mes3 = "Ago";
				mes2 = "Jul";
				mes1 = "Jun";
				break;
			case 9:
				mes3 = "Set";
				mes2 = "Ago";
				mes1 = "Jul";
				break;
			case 10:
				mes3 = "Out";
				mes2 = "Set";
				mes1 = "Jul";
				break;
			case 11:
				mes3 = "Nov";
				mes2 = "Out";
				mes1 = "Set";
				break;
			case 12:
				mes3 = "Dez";
				mes2 = "Nov";
				mes1 = "Out";
				break;

			default:
				System.out.println("Nao e valido");
			}
		} else
			System.out.println("Valor nao valido");
	}

	public void preProcessPDF(Object document) throws IOException, BadElementException, DocumentException {
		Document pdf = (Document) document;
		pdf.open();
		pdf.setPageSize(PageSize.A4);

		ExternalContext externalContext = FacesContext.getCurrentInstance().getExternalContext();
		String logo = externalContext.getRealPath("") + File.separator + "resources" + File.separator + "demo"
				+ File.separator + "images" + File.separator + "prime_logo.png";

		pdf.add(Image.getInstance(logo));
	}

}

esgc/src/main/webapp/page/acesso.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core">
<h:head>
	 <f:metadata>
		<f:viewAction action="#{acessoBean.registrarLog}" />
	</f:metadata>
	<meta http-equiv="refresh" content="#{acessoBean.link}" />
</h:head>
<h:body>

</h:body>
</html>

esgc/src/main/webapp/page/agua_anual.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:p="http://primefaces.org/ui"
	template="/page/esgc/esgc.xhtml">

	<ui:define name="pagina">
	<f:metadata>
			<f:viewAction action="#{aguaBean.carregarMes}" />
		</f:metadata>

	<h:form id="frm">
	<p:layout style="min-width:300px;min-height:92vh;">
				<!-- <p:layoutUnit position="west" resizable="true" size="50"
					minSize="40" maxSize="1000">

				</p:layoutUnit> -->
				<p:layoutUnit position="center" resizable="true">
		
		
		<p:dataTable id="rAgua" var="agua" value="#{aguaBean.aguasAnual}">
			<f:facet name="header" >
			<p></p>
			<p class="aw-page-subtitle">De acordo com o Decreto Estadual 42.601 de 16 de janeiro de 2016 o consumo deverá ser reduzido no mínimo em 10% em relação ao consumo do período do ano anterior. </p>
            <p/>
            <p class="aw-page-title">RELATÓRIO COMPARATIVO DE CONSUMO DE ÁGUA EM M³ no período de #{aguaBean.anoAnterior}/#{aguaBean.anoCorrente}</p>
        </f:facet >
				
				<p:columnGroup type="header">
				<p:row>
					<p:column rowspan="2" headerText="Ome" sortBy="#{agua.ome}" style="font-size:14px;"
						filterBy="#{agua.ome}" filterMatchMode="startsWith" width="62" filterPosition="top"/>
					<p:column rowspan="2" headerText="Matricula" width="75"/>
					<p:column rowspan="2" headerText="Cidade" priority="3"/>
					<p:column rowspan="2" headerText="Enderço" priority="3"/>
					<p:column colspan="3" headerText="#{aguaBean.anoAnterior}" priority="5"/>
					<p:column colspan="3" headerText="#{aguaBean.anoCorrente}" priority="5"/>
					<p:column colspan="2" headerText="Média Anual"/>
					<p:column headerText="Meta"/>
				</p:row>
				
				<p:row>
					<p:column headerText="#{aguaBean.mes1}" priority="5"/>
					<p:column headerText="#{aguaBean.mes2}" priority="5"/>
					<p:column headerText="#{aguaBean.mes3}" priority="5"/>
					<p:column headerText="#{aguaBean.mes1}" priority="5"/>
					<p:column headerText="#{aguaBean.mes2}" priority="5"/>
					<p:column headerText="#{aguaBean.mes3}" priority="5"/>
					<p:column id="ano_ant" headerText="#{aguaBean.anoAnterior}"/>
					<p:column id="ano_atu" headerText="#{aguaBean.anoCorrente}"/>
					<p:column headerText="Trimestre"/>
					
		 			<p:tooltip id="toolTip_ano_ant" for="ano_ant" value="média dos 12 meses do ano anterior" position="top"/>
		  			<p:tooltip id="toolTip_ano_atu" for="ano_atu" value="média dos meses corridos do ano vigente" position="top"/>
				</p:row>
			</p:columnGroup>

			<p:column >
				<p:outputLabel value="#{agua.ome}" />
			</p:column>
			<p:column>
				<p:outputLabel value="#{agua.matricula}" />
			</p:column>
		 	<p:column priority="3">
				<p:outputLabel value="#{agua.cidade}" />
			</p:column>
			<p:column priority="3">
				<p:outputLabel value="#{agua.endereco}" />
			</p:column>
		 	<p:column style='text-align:right' priority="5">
				<h:outputText value="#{agua.mes3AnoAnterior}">
				<f:convertNumber pattern="#,##0.00"
        		 locale="pt_BR" />
         		</h:outputText>
			</p:column> 
			<p:column style='text-align:right' priority="5">
				<h:outputText value="#{agua.mes2AnoAnterior}" >
				<f:convertNumber pattern="#,##0.00"
        		 locale="pt_BR" />
         		</h:outputText>
			</p:column> 
			<p:column style='text-align:right' priority="5">
				<h:outputText value="#{agua.mes1AnoAnterior}" >
				<f:convertNumber pattern="#,##0.00"
        		 locale="pt_BR" />
         		</h:outputText>
			</p:column> 
			<p:column style='text-align:right' priority="5">
				<h:outputText value="#{agua.mes3AnoAtual}" >
				<f:convertNumber pattern="#,##0.00"
        		 locale="pt_BR" />
         		</h:outputText>
			</p:column> 
			<p:column style='text-align:right' priority="5">
				<h:outputText value="#{agua.mes2AnoAtual}" >
				<f:convertNumber pattern="#,##0.00"
        		 locale="pt_BR" />
         		</h:outputText>
			</p:column> 
			<p:column style='text-align:right' priority="5">
				<h:outputText value="#{agua.mes1AnoAtual}" >
				<f:convertNumber pattern="#,##0.00"
        		 locale="pt_BR" />
         		</h:outputText>
			</p:column> 
			<p:column style='text-align:right'>
				<h:outputText value="#{agua.mediaTrimetreAnterior}" >
				<f:convertNumber pattern="#,##0.00"
        		 locale="pt_BR" />
         		</h:outputText>
			</p:column> 
			<p:column style='text-align:right'>
				<h:outputText value="#{agua.mediaTrimetreAtual}" >
				<f:convertNumber pattern="#,##0.00"
        		 locale="pt_BR" />
         		</h:outputText>
			</p:column>
				<p:column   	styleClass="#{(agua.mediaTrimetreAtual > agua.mediaTrimetreAnterior) and agua.mediaTrimetreAnterior != 0
																		 ?'aumentou' : agua.mediaTrimetreAnterior==agua.mediaTrimetreAtual  ? 
																		 'manteve' :  agua.mediaTrimetreAnterior == 0 ? 'impossivel' : 'diminuiu'}">
				<h:outputText value="#{agua.meta}"/>
			</p:column>
			
			
			<!-- <p:column>
				<h:outputText value="#{agua.thisYearProfit}%" />
			</p:column>
			<p:column>
				<h:outputText value="#{agua.lastYearAgua}">
					<f:convertNumber type="currency" currencySymbol="R$" />
				</h:outputText>
			</p:column>
			<p:column>
				<h:outputText value="#{agua.thisYearAgua}">
					<f:convertNumber type="currency" currencySymbol="R$" />
				</h:outputText>
			</p:column> 

			<p:columnGroup type="footer">
				<p:row>
					<p:column colspan="3" style="text-align:right" footerText="Totals:" />
					<p:column footerText="R$ #{aguaBean.lastYearTotal}" />

					<p:column footerText="R$ #{aguaBean.thisYearTotal}" />
				</p:row>
			</p:columnGroup>
-->
			<f:facet name="footer">
          
            
            <p:toolbar id="toolbar">
            	<f:facet name="right">
			 		 Período #{aguaBean.mes1}-#{aguaBean.mes3} #{aguaBean.dataAtual}
			  	</f:facet>
			</p:toolbar>
        </f:facet>
		</p:dataTable>
		</p:layoutUnit>
			</p:layout>
	</h:form>
	</ui:define>

</ui:composition>