esgc/br/gov/pe/pm/sgc/bean/CadastroContasBean.java
package br.gov.pe.pm.sgc.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import br.gov.pe.pm.sgc.model.Conta;
import br.gov.pe.pm.sgc.rn.ContaRn;
import br.gov.pe.pm.sgc.model.Grupo;
import br.gov.pe.pm.sgc.model.Imovel;
import br.gov.pe.pm.sgc.model.TipoConta;
import br.gov.pe.pm.sgc.rn.GrupoRn;
import br.gov.pe.pm.sgc.rn.ImovelRn;
import br.gov.pe.pm.sgc.rn.TipoContaRn;
import br.gov.pe.pm.sgc.util.method.MetodosUtil;

@Named("cadastroContasBean")
@ViewScoped
public class CadastroContasBean implements Serializable {

	private static final long serialVersionUID = -8339536807145293341L;
	private List<TipoConta> listaTipoContas;
	private List<Imovel> listaImovel;
	private TipoConta tipoConta = new TipoConta();
	private List<Conta> listaContas;
	private List<SelectItem> listaConta;
	private Conta conta = new Conta();
	private Conta contaAnterior = new Conta();
	private Imovel imovel = new Imovel();

	private Integer imov;
	// private String aux;

	public List<TipoConta> getListaTipoContas() {
		return listaTipoContas;
	}

	public void setListaTipoContas(List<TipoConta> listaTipoContas) {
		this.listaTipoContas = listaTipoContas;
	}

	public void setListaImovel(List<Imovel> listaImovel) {
		this.listaImovel = listaImovel;
	}

	public List<Imovel> getListaImovel() {
		return listaImovel;
	}

	public TipoConta getTipoConta() {
		return tipoConta;
	}

	public void setTipoConta(TipoConta tipoConta) {
		this.tipoConta = tipoConta;
	}

	public List<Conta> getListaContas() {
		return listaContas;
	}

	public void setListaContas(List<Conta> listaContas) {
		this.listaContas = listaContas;
	}

	public List<SelectItem> getListaConta() {
		return listaConta;
	}

	public void setListaConta(List<SelectItem> listaConta) {
		this.listaConta = listaConta;
	}

	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.contaAnterior = conta.clone();
		this.conta = conta;
	}

	public Conta getContaAnterior() {
		return contaAnterior;
	}

	public void setContaAnterior(Conta contaAnterior) {
		this.contaAnterior = contaAnterior;
	}

	public Imovel getImovel() {
		return imovel;
	}

	public void setImovel(Imovel imovel) {
		this.imovel = imovel;
	}

	public Integer getImov() {
		return imov;
	}

	public void setImov(Integer imov) {
		this.imov = imov;
	}

// Methods

	@PostConstruct
	public void init() {
		this.imov = Integer
				.parseInt((String) FacesContext.getCurrentInstance().getExternalContext().getFlash().get("imov"));

		System.out.println("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB " + this.imov);
		imovel = new ImovelRn().carregar(this.imov);
		this.conta.setImovel(imovel);
		listar();

	}

	public void listar() {
		this.listaContas = new ContaRn().listarPorImovel(imovel);

	}

	public CadastroContasBean() {
		imovel = new Imovel();
		conta.setImovel(imovel);

	}

	public String excluirConta() {
		new ContaRn().excluir(this.conta);
		contaAnterior = new Conta();
		listar();
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Registro excluído com sucesso!", null);
		FacesContext.getCurrentInstance().addMessage(null, message);
		return null;
	}

	/*
	 * public void listarPorOme() { this.setListaImovel(new
	 * ImovelRn().listarPorOme(omeView.getIdOrganizacao())); }
	 */

	public String removeAcentos(String s) {
		return new MetodosUtil().removeAcentos(s);
	}

	public List<SelectItem> getListarTipoContas() {
		List<SelectItem> listaTipoConta = new ArrayList<SelectItem>();
		List<TipoConta> tipoContas = new TipoContaRn().listarAtivos();
		listaTipoConta.add(new SelectItem(null, "Selecione..."));
		for (TipoConta tc : tipoContas) {
			listaTipoConta.add(new SelectItem(tc.getIdTipoConta(), tc.getDescricao()));

		}
		return listaTipoConta;

	}

	public List<SelectItem> getListarGrupos() {
		List<SelectItem> listaGrupo = new ArrayList<SelectItem>();
		listaGrupo.add(new SelectItem(null, "Selecione..."));
			if (this.conta.getTipoConta().getIdTipoConta() != (null) && !(this.conta.getTipoConta().getIdTipoConta().equals(null))) {
				List<Grupo> grupo = new GrupoRn().listarAtivoConta(this.conta.getTipoConta());
				for (Grupo g : grupo) {
					listaGrupo.add(new SelectItem(g.getIdGrupo(), g.getGrupo()));
				}
			return listaGrupo;
		}
		return null;
	}

	public void novo() {

		this.conta = new Conta();
		contaAnterior = new Conta();
		this.conta.setStatus(true);
		this.conta.setImovel(imovel);
		this.conta.getTipoConta().setIdTipoConta(getTipoConta().getIdTipoConta());
		
		
	}

	public void salvar() {
		this.conta = new ContaRn().salvar(this.contaAnterior, this.conta);
		listar(); // mensagem de sucesso FacesMessage message = new
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Registro salvo com sucesso!", null);
		FacesContext.getCurrentInstance().addMessage(null, message);
		RequestContext.getCurrentInstance().update(Arrays.asList("msgs", "tb_conta"));
	}

	

	public String editar(String id) {
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("id", id);
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("call", "1");
		return "cadastro_contas?faces-redirect=true";

	}

}

esgc/br/gov/pe/pm/sgc/bean/LancamentoFaturaBean.java
package br.gov.pe.pm.sgc.bean;

import java.io.Serializable;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.faces.model.SelectItem;
import javax.faces.view.ViewScoped;
import javax.inject.Named;

import org.primefaces.context.RequestContext;

import br.gov.pe.pm.sgc.entity.entityview.OmeView;
import br.gov.pe.pm.sgc.model.Competencia;
import br.gov.pe.pm.sgc.model.Conta;
import br.gov.pe.pm.sgc.model.Imovel;
import br.gov.pe.pm.sgc.model.TipoConta;
import br.gov.pe.pm.sgc.model.TipoFatura;
import br.gov.pe.pm.sgc.rn.CompetenciaRn;
import br.gov.pe.pm.sgc.rn.ContaRn;
import br.gov.pe.pm.sgc.rn.ImovelRn;
import br.gov.pe.pm.sgc.rn.OmeRn;
import br.gov.pe.pm.sgc.rn.TipoContaRn;
import br.gov.pe.pm.sgc.rn.TipoFaturaRn;
import br.gov.pe.pm.sgc.util.method.MetodosUtil;


@Named("lancamentoFaturaBean")
@ViewScoped
public class LancamentoFaturaBean implements Serializable {


	private static final long serialVersionUID = 1L;
	public LancamentoFaturaBean() {};
	private OmeView omeView = new OmeView();
	private List<SelectItem> listaFatura;
	private List<Conta> listaConta;
	private List<Competencia> listaCompetencia;
	private Competencia competencia = new Competencia();
	private Competencia competenciaAnterior = new Competencia();
	private Conta conta = new Conta();
	private Conta contaAnterior = new Conta();
	private Imovel imovel = new Imovel();
	private List<Conta> ListaContas = new ArrayList<Conta>();
	private List<Imovel> listaImovel;
	private String ncm;
	private Double consumoP;
	private Double consumoT;
	private String teste;
	private Integer tipoConta;
	//private Integer tipoFatura;
	//private Integer idIm;
	//private Integer idOm;

//	public Integer getIdIm() {
//		return this.idIm =imovel.getIdImovel() ;
//	}
//
//	public void setIdIm(Integer idIm) {
//		this.idIm = idIm;
//	}
//
//	public Integer getIdOm() {
//		return this.idOm =imovel.getIdOme();
//	}
//
//	public void setIdOm(Integer idOm) {
//		this.idOm = idOm;
//	}

//	public Integer getTipoFatura() {
//		return tipoFatura;
//	}
//
//	public void setTipoFatura(Integer tipoFatura) {
//		this.tipoFatura = tipoFatura;
//	}

	public Integer getTipoConta() {
		return tipoConta;
	}

	public void setTipoConta(Integer tipoConta) {
		this.tipoConta = tipoConta;
	}

	public Imovel getImovel() {
		return imovel;
	}

	public List<Conta> getListaContas() {
		return ListaContas;
	}

	public void setListaContas(List<Conta> listaContas) {
		ListaContas = listaContas;
	}

	public void setImovel(Imovel imovel) {		
		this.imovel = imovel;
	}

	public OmeView getOmeView() {
		return omeView;
	}

	public void setOmeView(OmeView omeView) {
		this.omeView = omeView;
	}

	public List<SelectItem> getListaFatura() {
		return listaFatura;
	}

	public void setListaFatura(List<SelectItem> listaFatura) {
		this.listaFatura = listaFatura;
	}

	public List<Conta> getListaConta() {
		return listaConta;
	}

	public void setListaConta(List<Conta> listaConta) {
		this.listaConta = listaConta;
	}

	public List<Competencia> getListaCompetencia() {
		return listaCompetencia;
	}

	public void setListaCompetencia(List<Competencia> listaCompetencia) {
		this.listaCompetencia = listaCompetencia;
	}

	public Competencia getCompetencia() {
		return competencia;
	}

	public void setCompetencia(Competencia competencia) {
		this.competenciaAnterior= competenciaAnterior.clone();
		this.competencia = competencia;
	}

	public Competencia getCompetenciaAnterior() {
		return competenciaAnterior;
	}

	public void setCompetenciaAnterior(Competencia competenciaAnterior) {		
		this.competenciaAnterior = competenciaAnterior;
	}

	public Conta getConta() {
		return conta;
	}

	public void setConta(Conta conta) {
		this.contaAnterior = conta.clone();
		this.conta = conta;
	}

	public Conta getContaAnterior() {
		return contaAnterior;
	}

	public void setContaAnterior(Conta contaAnterior) {
		this.contaAnterior = contaAnterior;
	}

	public void listarConta() {
		this.setListaConta(new ContaRn().listar());
	}

	public void listarCompetencia() {
		this.setListaCompetencia(new CompetenciaRn().listar());
	}
	
	public void listarCompetenciaPorTipoConta() {
		this.setListaCompetencia(new CompetenciaRn().listar(this.competencia.getTipoConta()));
	}
	private Date comp;
	public Date getComp() {
		return comp;
	}

	public void setComp(Date comp) {
		this.comp = comp;
	}


	public void listarCompetenciaPorCompetencia() {
		System.out.println("!!!!!!!!!!!!!!!!!!!!!!!!!");
		
		System.out.println(this.competencia.getTipoConta()+ " $$ "+  this.competencia.getCompetencia());
		/*
		 * System.out.println(this.competencia.getTipoConta()+ " $$ "+ getComp());
		 * DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");
		 * LocalDate data = LocalDate.parse("01/12/2019", formato);
		 */
		
		//this.competencia.setCompetencia(new Date("01/12/2019"));
		this.competencia.setTipoConta(new TipoContaRn().carregar(tipoConta));
		this.competencia.setCompetencia(getComp());
		this.setListaCompetencia(new CompetenciaRn().listar(this.competencia.getTipoConta(), this.competencia.getCompetencia()));
	}

	public void listarCompetenciaPorConta() {
		this.setListaCompetencia(new CompetenciaRn().listar(this.competencia.getTipoConta(), this.competencia.getCompetencia(), this.conta));
	}
	
	


	public List<SelectItem> getListarTipoFatura() {
		if (this.listaFatura == null) {
			this.listaFatura = new ArrayList<SelectItem>();
			List<TipoFatura> tf = new TipoFaturaRn().listar();
			this.listaFatura.add(new SelectItem(null, "Selecione..."));
			for (TipoFatura f : tf) {
				this.listaFatura.add(new SelectItem(f.getIdTipoFatura(), f.getDescricao()));
			}

		}
		return listaFatura;
	}
	public List<SelectItem> getListarGrupoContas() {
		
		List<SelectItem> listaTipoConta = new ArrayList<SelectItem>();	
		List<TipoConta> tipoContas = new TipoContaRn().listarAtivos();
		listaTipoConta.add(new SelectItem(null, "Selecione..."));
		for (TipoConta tc : tipoContas) {
			listaTipoConta.add(new SelectItem(tc.getIdTipoConta(), tc.getDescricao()));

		}
		System.out.println("@@@@@@@@@@@@@@@@@@@@@@@ " + listaTipoConta.get(0).getLabel());
		return listaTipoConta;
	}

	public void adcionar() {
		this.conta = new Conta();
		contaAnterior = new Conta();
		this.conta.setStatus(true);
		this.competencia = new Competencia();
		competenciaAnterior = new Competencia();
	}

	
	 public void editar(Competencia competencia) { //setCompetencia(new
	// CompetenciaRn().carregar(idCompetencia);
		 System.out.println("&&&&&&&&& "+competencia);
		 setCompetencia(competencia);
		// System.out.println("&&&&&&&&&@@ "+this.competencia);
	 setTipoConta(this.competencia.getTipoConta().getIdTipoConta());
	 
	
	 setTipoConta(this.competencia.getTipoConta().getIdTipoConta());
	setComp(this.competencia.getCompetencia());
	 setNcm(this.competencia.getConta().getnContratoMatricula());
	 setConta(this.competencia.getConta());
	 carregarDados();
	 setOmeView(new OmeRn().carregar(this.competencia.getImovel().getIdOme()));
	 listarCompetencia(); System.out.println("#################  " +
	 omeView.getSigla()); setConta(this.competencia.getConta());
	 setConsumoT(this.competencia.getConsumo());
	 
	 }
	 
	/*public String editar(String id) {
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("id", id);
		FacesContext.getCurrentInstance().getExternalContext().getFlash().put("call", "1");
		return "lancamento_faturas?faces-redirect=true";
	}*/
	
	
	public String excluir() {
		new ContaRn().excluir(this.conta);
		contaAnterior = new Conta();
		new CompetenciaRn().excluir(this.competencia);
		competenciaAnterior = new Competencia();
		//listarConta();
		listarCompetencia();
		setCompetencia(new Competencia());
		FacesMessage message = new FacesMessage(FacesMessage.SEVERITY_INFO, "Registro excluído com sucesso!", null);
		FacesContext.getCurrentInstance().addMessage(null, message);
		return null;
	}

	public void salvar() {
		System.out.println("1111111111111111111111111111111" + this.competencia);
		//this.competencia.getTipoConta().setIdTipoConta(1);//////
		//this.competencia.setTipoFatura(new TipoFaturaRn().carregar(this.tipoFatura)); ///////
		System.out.println("1111111111111111111111111111111" + this.ncm);
		//this.conta = new ContaRn().carregarNCM(this.ncm); // alterado 19/05 pela manha
		this.competencia.setConsumo(consumoT);
		
		this.competencia.setCompetencia(comp); // alterado 19/05 pela manha
		
		System.out.println("#######!!!!!!!!! " + this.conta);
		
		System.out.println("#######!!!!!!!!! " + this.conta.getIdConta());
		this.competencia.setConta(new ContaRn().carregar(this.conta.getIdConta()));	
		
		System.out.println("#######!!!!!!!!! " + this.conta +" ###!!!! " + this.conta.getImovel()); //this.conta continua vazio
		this.competencia.getImovel().setIdImovel(this.conta.getImovel().getIdImovel());
		this.competencia.setTipoConta(new TipoContaRn().carregar(this.tipoConta));
		//this.competencia.getImovel().setIdImovel(this.conta.getImovel().getIdImovel());
		//this.competencia.getImovel().setIdOme(this.omeView.getIdOrganizacao());		
		//this.competencia.getImovel().setIdImovel(idIm);
		//this.competencia.getConta().setIdConta(idOm);
		System.out.println("$$$$$$$$$$"+consumoT);
		System.out.println("%%%%"+this.competencia.getImovel().getIdImovel());
		System.out.println("#######"+this.competencia.getConta().getIdConta());		
		System.out.println("1111111111111111111111111111111" + this.competencia.getValor());
		this.competencia = new CompetenciaRn().salvar(this.competenciaAnterior,this.competencia);
		listarCompetenciaPorCompetencia();
		this.consumoT = null;
		this.consumoP = null;
		this.omeView = null;
		this.conta = new Conta();
		this.imovel = new Imovel();
		this.ncm = null;
		this.comp = null;
		this.competencia = new Competencia();
	
		
		// mensagem de sucesso

esgc/br/gov/pe/pm/sgc/entity/entityview/OmeView.java
package br.gov.pe.pm.sgc.entity.entityview;



public class OmeView {

	private Integer idOrganizacao;	
	private Boolean ativo;	
	private String nome;
	private Boolean status;
	private String sigla;
	private String bairro;
	private String cep;
	private String cidade;
	private String complemento;
	private String logradouro;
	private String numero;
	private String pontoReferencia;
	private String telefone;
	
	

	
	public Integer getIdOrganizacao() {
		return idOrganizacao;
	}
	public void setIdOrganizacao(Integer idOrganizacao) {
		this.idOrganizacao = idOrganizacao;
	}
	public Boolean getAtivo() {
		return ativo;
	}
	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getSigla() {
		return sigla;
	}
	public void setSigla(String sigla) {
		this.sigla = sigla;
	}
	public Boolean getStatus() {
		return status;
	}
	public void setStatus(Boolean status) {
		this.status = status;
	}
	public String getBairro() {
		return bairro;
	}
	public void setBairro(String bairro) {
		this.bairro = bairro;
	}
	public String getCep() {
		return cep;
	}
	public void setCep(String cep) {
		this.cep = cep;
	}
	public String getCidade() {
		return cidade;
	}
	public void setCidade(String cidade) {
		this.cidade = cidade;
	}
	public String getComplemento() {
		return complemento;
	}
	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}
	public String getLogradouro() {
		return logradouro;
	}
	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}
	public String getNumero() {
		return numero;
	}
	public void setNumero(String numero) {
		this.numero = numero;
	}
	public String getPontoReferencia() {
		return pontoReferencia;
	}
	public void setPontoReferencia(String pontoReferencia) {
		this.pontoReferencia = pontoReferencia;
	}
	public String getTelefone() {
		return telefone;
	}
	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}
	
	

	

}

esgc/src/main/java/br/gov/pe/pm/esgc/bean/CompesaBean.java
package br.gov.pe.pm.esgc.bean;

public class CompesaBean {

}

esgc/src/main/webapp/page/esgc/esgc.xhtml
<ui:composition template="/WEB-INF/template.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:composite="http://xmlns.jcp.org/jsf/composite">


	<ui:define name="conteudo">

		<p:layout>
			<p:layoutUnit position="west"  collapsed="false" collapsible="true" id="esgc_tree" size="230"
				resizable="true" header="Geral" gutter="0" >
				<ui:include src="esgc_tree.xhtml" />
			</p:layoutUnit>

			<p:layoutUnit position="center" collapsible="true" id="esgc_pagina"
				gutter="0">
				<ui:insert name="pagina" />
			</p:layoutUnit>
		</p:layout>
		
	</ui:define>


</ui:composition>

esgc/src/main/webapp/page/esgc/grupos.xhtml
<ui:composition template="/page/esgc/esgc.xhtml"
	xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://xmlns.jcp.org/jsf/html"
	xmlns:f="http://xmlns.jcp.org/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
	xmlns:composite="http://xmlns.jcp.org/jsf/composite"
	xmlns:fn="http://java.sun.com/jsp/jstl/functions">

	<ui:define name="pagina">
 
		<f:metadata>
			<f:viewAction action="#{grupoBean.listar}" />
		</f:metadata>
 

		<div class="conteudo_titulo">Tipos de Grupos de Demandas</div>
		<div style="width: 98%; margin: 0 auto;">
			<h:form id="frm">

				<p:growl id="msgs" sticky="false" life="3000" />

				<p:toolbar id="toolbar">
					<f:facet name="left">
						<p:commandButton icon="ui-icon-help" id="ajuda_grupo"
							oncomplete="popupwindow('/esgc/page/ajuda/ajuda_grupo.xhtml', 'newwindow');"
							alt="Ajuda" title="Ajuda">
						</p:commandButton>
					</f:facet>

					<f:facet name="right">
						<p:commandButton icon="ui-icon-arrowthick-1-s"
							alt="Download em .xls" title="Download em .xls" ajax="false"
							immediate="true">
							<p:dataExporter type="xls" target="grupo" fileName="Grupo" />
						</p:commandButton>

						<span class="ui-separator"> <span
							class="ui-icon ui-icon-grip-dotted-vertical" />
						</span>

						<p:commandButton value="Novo" icon="ui-icon-document" alt="Novo"
							title="Novo" action="#{grupoBean.novo}" process="@this"
							update="dialog_grupo" oncomplete="PF('edicaoGrupoDialog').show()">
							<p:resetInput target="dialog_grupo" />
						</p:commandButton>
					</f:facet>
				</p:toolbar>

				<p:dataTable id="grupo" reflow="true"
					value="#{grupoBean.listaGrupo}" var="grupo" rows="10"
					paginator="true" widgetVar="grupo" paginatorPosition="bottom"
					rowKey="#{grupo.idGrupos}"
					emptyMessage="Nenhum registro encontrado."
					paginatorTemplate=" {CurrentPageReport} {FirstPageLink} {PreviousPageLink} {PageLinks}     
                                   {NextPageLink} {LastPageLink} {RowsPerPageDropdown} #{fn:length(grupoBean.listaGrupo)} Tipo de Grupos Cadastrados"
					rowsPerPageTemplate="10,20,50,100">


					<p:column width="67" exportable="false">
						<p:commandButton icon="ui-icon-pencil" alt="Editar" title="Editar"
							process="@this" update="dialog_grupo"
							oncomplete="PF('edicaoGrupoDialog').show()"
							style="margin-right: 7px">
							<p:resetInput target="dialog_grupo" />
							<f:setPropertyActionListener value="#{grupo}" target="#{grupoBean.grupo}" />
						</p:commandButton>

						<p:commandButton action="#{grupoBean.excluir}"
							update="grupo frm:msgs" icon="ui-icon-trash" alt="Excluir"
							title="Excluir" process="@this">
							<f:setPropertyActionListener value="#{grupo}" target="#{grupoBean.grupo}" />
							<p:confirm header="Confirmação" icon="ui-icon-alert" message="Tem certeza que deseja excluir?" />
						</p:commandButton>
					</p:column>


					<p:column headerText="Conta" sortBy="#{grupo.tipoConta.descricao}"
						filterBy="#{grupo.tipoConta.descricao}#{grupoBean.removeAcentos(grupo.tipoConta.descricao)}"
						filterMatchMode="contains">
						<h:outputText value="#{grupo.tipoConta.descricao}" >
						<!-- 	<f:converter converterId="TipoContaConverter" /> -->
						</h:outputText>						
					</p:column>

					<p:column headerText="Descrição" sortBy="#{grupo.grupo}"
						filterBy="#{grupo.grupo}#{grupoBean.removeAcentos(grupo.grupo)}"
						filterMatchMode="contains">
						<h:outputText value="#{grupo.grupo}" />
					</p:column>

					<p:column headerText="Ativo" filterBy="#{grupo.status}"
						filterMatchMode="exact">
						<f:facet name="filter">
							<p:selectOneMenu onchange="PF('grupo').filter()">
								<f:converter converterId="javax.faces.Boolean" />
								<f:selectItem itemLabel="Todos" itemValue="" />
								<f:selectItem itemLabel="Sim" itemValue="true" />
								<f:selectItem itemLabel="Não" itemValue="false" />
							</p:selectOneMenu>
						</f:facet>
						<h:outputText value="#{grupo.status ? 'SIM': 'NÃO'}" />
					</p:column>
					
				</p:dataTable>

			</h:form>
		</div>

		<p:dialog header="Cadastro de Grupos de Demanda" responsive="true"
			widgetVar="edicaoGrupoDialog" id="dialog_grupo" resizable="false"
			modal="true" closeOnEscape="true" appendTo="@(body)">

			<h:form id="frm_dialog" prependId="false">

				<p:messages id="msgs_dialog" />
				<p:defaultCommand target="btn_salvar" scope="dialog_grupo" />
				<h:inputHidden id="id_grupo" value="#{grupoBean.grupo.idGrupo}" />
				<f:param name="frm" value="#{grupoBean.grupo.idGrupo}" /> 
				

				<div class="ui-fluid">

					<p:panelGrid columns="2" id="painel_edicao_dialog" layout="grid"
						columnClasses="ui-grid-col-4,ui-grid-col-8"
						styleClass="ui-panelgrid-blank">

						<p:outputLabel value="Conta" for="conta" />
						<p:selectOneMenu id="conta" label="Conta" size="30"
							maxlength="40" required="true" onkeyup="alteraMaiusculo()"
							requiredMessage="O campo descrição é obrigatório."
							value="#{grupoBean.grupo.tipoConta.idTipoConta}">							
							<f:selectItems value="#{grupoBean.listarTipoContas}" />	
													
						</p:selectOneMenu>
												
						<p:outputLabel value="Descrição" for="descricao" />
						<p:inputText id="descricao" label="Descrição" size="30"
							maxlength="40" required="true" onkeyup="alteraMaiusculo()"
							requiredMessage="O campo descrição é obrigatório."
							value="#{grupoBean.grupo.grupo}">
						</p:inputText>



						<p:outputLabel value="Ativo" for="ativo" />
						<p:selectBooleanButton id="ativo" label="Ativo" onLabel="SIM"
							required="true" offLabel="NÃO" value="#{grupoBean.grupo.status}"
							style="width: 100px" />

					</p:panelGrid>

					<br />
					<p:separator />
					<p:outputPanel
						style="margin: 20px 0px 20px 0px; width: 100%; display: table;">
						<p:commandButton id="btn_salvar" value="Salvar"
							icon="ui-icon-check" action="#{grupoBean.salvar}"
							process="dialog_grupo" update="msgs_dialog painel_edicao_dialog"
							oncomplete="if(!args.validationFailed) PF('edicaoGrupoDialog').hide()"
							style="float: right; width: 100px" >
							<p:resetInput target="dialog_grupo" />
						</p:commandButton>
					</p:outputPanel>
				</div>

			</h:form>

		</p:dialog>

	</ui:define>

</ui:composition>